#!/bin/sh

if [ -L $0 ] ; then
    DIR=$(dirname "$(readlink -f "$0")") ;
else
    DIR=$(dirname "$0") ;
fi ;

cd "$DIR"

export TERM='xterm-256color'

if [ -d "$DIR/venv" ] && [ -f "$DIR/venv/bin/python3" ]; then
    exec "$DIR/venv/bin/python3" -m arsenal "$@"
else
    exec python3 -m arsenal "$@"
fi
